steps:
 - name: 'node'
   entrypoint: 'npm'
   args: ['install']
 - name: 'node'
   entrypoint: 'npm'
   args: ['build']
 - name: 'node'
   entrypoint: 'sh'
   args: ['-c', 'ls -ltr']
 - name: 'node'
   entrypoint: 'sh'
   args: ['-c', 'cd target && ls -ltr']   
 ## Docker Build
 #- name: 'gcr.io/cloud-builders/docker'
 #  args: ['build', '-t', 
 #         'gcr.io/$PROJECT_ID/vue-crl:${SHORT_SHA}', '.']
 ## Deploy to Cloud Run
 #- name: google/cloud-sdk
 #  args: ['gcloud', 'run', 'deploy', 'vue-crl:${SHORT_SHA}', 
 #         '--image=gcr.io/$PROJECT_ID/vue-crl:${SHORT_SHA}', 
 #         '--region', 'asia-southeast2', '--platform', 'managed', 
 #         '--allow-unauthenticated']